<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRSxs5To\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRSxs5To/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRSxs5To.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRSxs5To\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRSxs5To\App_KernelDevDebugContainer([
    'container.build_hash' => 'RSxs5To',
    'container.build_id' => '385f4ba9',
    'container.build_time' => 1696508355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRSxs5To');
