<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'amount' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_object-create-9b64a1.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_f-a40ca4.js',
                '/build/amount.js',
            ],
        ],
        'invoice' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_export_js-node_modules_core-js_internals_object-create-9b64a1.js',
                '/build/invoice.js',
            ],
        ],
    ],
],

]];
